project:
  type: website
  output-dir: docs
  resources:
    - R/
    - data/

website:
  title: "Benny's Coding Notebook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: YRBS Models
        menu:
          - href: models/datasets.qmd
            text: Data and Research Question
          - href: models/logistic.qmd
            text: Logistic Regression
          - href: models/lasso.qmd
            text: Lasso Regression
          - href: models/trees.qmd
            text: Decision Trees
          - href: models/random_forest.qmd
            text: Random Forest
      - text: Trading
        menu:
          - href: Kalshi/KalshiUpToMay.qmd
            text: Trading (May)
          - href: Kalshi/KalshiUpToJune.qmd
            text: Trading (June)
          - href: Kalshi/KalshiUpToJuly.qmd
            text: Trading (July)
          - href: Kalshi/KalshiMorality.qmd
            text: Kalshi's Morality
      - text: Jazz Progression LLM
        menu:
          - href: Jazz Generation/JazzGenerationOutline.qmd
            text: Project Background and Outline
          - href: Jazz Generation/JazzGenerationDatasetCreation.qmd
            text: Dataset Creation
          - href: Jazz Generation/JazzGeneration.qmd
            text: Bigram Markov Model
          - href: Jazz Generation/JazzGenerationSecond.qmd
            text: Bigram Markov Model 2.0
          - href: Jazz Generation/JazzGenerationExperiment.qmd
            text: |
              Published Model<br><em>(with played examples)</em>
        



format:
  html:
    theme: minty
    css: styles.css
    toc: true


