---
title: "Benny's Coding Notebook"
---
<br>
This website will be my coding notebook, where I explore a variety of analyses in R. It's meant to be part journal, part portfolio.
<br>

### What You'll Find Here

- **About Me**: A little bit about me and my research interests.  

-   **YRBS Models**: This is a collection of machine learning models I coded using the Youth Risk Behavior Survey (YRBS) 2023 dataset. In this, I will implement and understand different modeling techniques using the `tidymodels` framework in R. Included are examples of:

    -   Logistic Regression
    -   Lasso Regression
    -   Decision Trees
    -   Random Forest
    
- **Summer 2025 Trading Journal**: This is a personal journal of my first experience trading, with a focus on capturing the journey of improvement over the summer. In it, I use R code and personal narrative to analyze trading habits and results. The emphasis here is less on the coding and more on the outcome; less serious and more light-hearted. 

- **Jazz Progression LLM**: This is a personal project of mine - building a generative model to create jazz chord progressions. In this collection, I describe the model's inspiration, build a dataset from scratch, and showcase the code I wrote (as well as updates I implemented) along the way to creating my custom Markov model. All work was done in R.

